"""COUNTRY dimension of the IMF.STA,IRFCL dataflow for indicator
IRFCLDT1_IRFCL56V_FTO / sector S1XS1311 (monetary gold, official reserves) --
snapshot of https://api.imf.org/external/sdmx/2.1/data/IMF.STA,IRFCL/
.IRFCLDT1_IRFCL56V_FTO.S1XS1311.M (empty COUNTRY = wildcard), 28.09.2026.
88 entries: 86 ISO3 countries + 2 aggregates (EZB = European Central Bank,
G163 = Euro Area). Used only to generate catalog descriptions -- the fetch
itself reads the COUNTRY id straight off each API response, never off this
file, so a country IMF adds later still round-trips (with a generic
description) even before this file is refreshed.
"""
COUNTRY_NAMES = {
    'AGO': 'Angola',
    'ALB': 'Albania',
    'ARG': 'Argentina',
    'ARM': 'Armenia, Republic of',
    'AUS': 'Australia',
    'AUT': 'Austria',
    'BEL': 'Belgium',
    'BGR': 'Bulgaria',
    'BLR': 'Belarus, Republic of',
    'BOL': 'Bolivia',
    'BRA': 'Brazil',
    'CAN': 'Canada',
    'CHE': 'Switzerland',
    'CHL': 'Chile',
    'CHN': "China, People's Republic of",
    'COL': 'Colombia',
    'CRI': 'Costa Rica',
    'CYP': 'Cyprus',
    'CZE': 'Czech Republic',
    'DEU': 'Germany',
    'DNK': 'Denmark',
    'DOM': 'Dominican Republic',
    'ECU': 'Ecuador',
    'EGY': 'Egypt, Arab Republic of',
    'ESP': 'Spain',
    'EST': 'Estonia, Republic of',
    'EZB': 'European Central Bank (ECB)',
    'FIN': 'Finland',
    'FRA': 'France',
    'G163': 'Euro Area (EA)',
    'GBR': 'United Kingdom',
    'GEO': 'Georgia',
    'GRC': 'Greece',
    'GTM': 'Guatemala',
    'HKG': "Hong Kong Special Administrative Region, People's Republic of China",
    'HND': 'Honduras',
    'HRV': 'Croatia, Republic of',
    'HUN': 'Hungary',
    'IDN': 'Indonesia',
    'IND': 'India',
    'IRL': 'Ireland',
    'ISL': 'Iceland',
    'ITA': 'Italy',
    'JAM': 'Jamaica',
    'JOR': 'Jordan',
    'JPN': 'Japan',
    'KAZ': 'Kazakhstan, Republic of',
    'KGZ': 'Kyrgyz Republic',
    'KHM': 'Cambodia',
    'KOR': 'Korea, Republic of',
    'LKA': 'Sri Lanka',
    'LTU': 'Lithuania, Republic of',
    'LUX': 'Luxembourg',
    'LVA': 'Latvia, Republic of',
    'MAR': 'Morocco',
    'MDA': 'Moldova, Republic of',
    'MEX': 'Mexico',
    'MKD': 'North Macedonia, Republic of',
    'MLT': 'Malta',
    'MNG': 'Mongolia',
    'MUS': 'Mauritius',
    'MYS': 'Malaysia',
    'NIC': 'Nicaragua',
    'NLD': 'Netherlands, The',
    'NOR': 'Norway',
    'NZL': 'New Zealand',
    'PER': 'Peru',
    'PHL': 'Philippines',
    'POL': 'Poland, Republic of',
    'PRT': 'Portugal',
    'PRY': 'Paraguay',
    'ROU': 'Romania',
    'RUS': 'Russian Federation',
    'SAU': 'Saudi Arabia',
    'SGP': 'Singapore',
    'SLV': 'El Salvador',
    'SRB': 'Serbia, Republic of',
    'SVK': 'Slovak Republic',
    'SVN': 'Slovenia, Republic of',
    'SWE': 'Sweden',
    'THA': 'Thailand',
    'TUN': 'Tunisia',
    'TUR': 'Türkiye, Republic of',
    'UKR': 'Ukraine',
    'URY': 'Uruguay',
    'USA': 'United States',
    'WBG': 'West Bank and Gaza',
    'ZAF': 'South Africa',
}
